---
- name: Single source of information for all files
  assemble:
    src: "{{ filedirPostPatch }}/{{ ansible_hostname }}"
    dest: "{{ filedirPostPatch }}/{{ ansible_hostname}}.PostCheckInfo.txt"
    delimiter: '--------------------------------------------------------------------------------'
  delegate_to: localhost
